version: '3.7'
services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '8307:${MYSQL_PORT}'
    expose:
      - '${MYSQL_PORT}'
    command: --init-file /datamodel/init.sql
    volumes:
      - ./volumes/init.sql:/datamodel/init.sql

  scrapperdatahandler:   
    build:
      context: ./datamodel
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - mysqldb
    networks:     
     - default
    ports:
      - "8083:${STOREDATA_PORT}" 
     
  scrapperservice:
    build:
      context: ./application
      dockerfile: Dockerfile
    env_file: .env
    depends_on: 
      - scrapperdatahandler
    networks:
      - default
    ports:
      - "8084:${SCRAPPER_PORT}"

volumes:
  volumes:

